version: "3"
services:
  # Eureka Service
  service-registry:
    container_name: service-registry
    build: ./srvcregistry
    ports:
      - "8761:8761"

  # API Gateway
  api-gateway:
    container_name: api-gateway
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    networks:
      - api

  # Auth Service
  auth-service:
    container_name: auth-service
    build: ./auth
    ports:
      - "5000:5000"
    networks:
      - api
      - auth-network
    depends_on:
      - auth-db
      - service-registry
  auth-db:
    image: 'postgres:latest'
    container_name: auth-db
    networks:
      - auth-network
    environment:
      - 'POSTGRES_DB=auth-db'
      - 'POSTGRES_PASSWORD=auth8192024'
      - 'POSTGRES_USER=kaon'
    ports:
      - '5432:5432'

  # User Service & DB
  users-service:
    container_name: users-service
    build: ./users
    depends_on:
      - service-registry
      - users-db
    networks:
      - api
      - users-network
    ports:
      - "8082:8082"
  users-db:
    image: 'postgres:latest'
    container_name: users-db
    networks:
      - users-network
    environment:
      - 'POSTGRES_DB=users-db'
      - 'POSTGRES_PASSWORD=users8162024'
      - 'POSTGRES_USER=kaon'
    ports:
      - '5433:5432' # host:container (can access 5432 of container thru 5433)
  
networks:
  api:
  auth-network:
  users-network: